### ISSUE TITLE
Wrap Defined Macros to python 3.x.x

### ISSUE THREAD

**Issue by scorp08** [Alan-R/ctypesgen#7]
Hello
I was planning to use ctypesgen to wrap some c files to python. Did some wrapping but can not inclueded  macros in headers or c files.  is `t_INITIAL_pp_define` in pplexer be used , how can wrap macros ?
Thnks

**Comment by Alan-R** [comment]
In the Assimilation code, I make use of quite a few macros in header files, IIRC. 

In fact, lots of C code won't work if macros weren't included. One I was just looking at was macros used to size arrays. This is a typical C macro, which I've use a lot, and seems to work for me:

#define DIMOF(a) (sizeof(a)/sizeof((a)[0])

I'm pretty sure I would notice if macros weren't working. In fact, this one wasn't working when I initially tried it in Python 3, since division is now floating point division in Python 3. So, when an array size was computed I had to put int(DIMOF(foo)) into the code. Since I had to do that, that means it was using macros. 

Make sure you're processing the C _header_ file with the macro definition in it.

Can you attach a simple example which isn't working?

**Comment by scorp08** [comment]
`#ifdef NO_BOMBING_MACROS
#define BU_CKMAG(_ptr, _magic, _str) BU_IGNORE((_ptr))
#else
#define BU_CKMAG(_ptr, _magic, _str) { \
 
const uintptr_t _ptrval = (const uintptr_t) (_ptr);
 
if (UNLIKELY
    ((_ptrval == 0) || (_ptrval & (sizeof(_ptrval) - 1))
     || *((const uint32_t *) (_ptr)) != (uint32_t) (_magic)))
{
 
bu_badmagic((const uint32_t *) (_ptr), (uint32_t) _magic, _str, __FILE__,
            __LINE__);
 
}
 
}
 
#endif`

badmagic is ok but BU_CKMAG not in .py.

**Comment by scorp08** [comment]
Also there is a problem with `UNCHECKED ` in preambles.py. It cause to  function return type to `c_void_p` no matter what it gets (tried with c_int,c_float, c_char_p). Seems that need to put an `__type__.encode()` ?

**Comment by Alan-R** [comment]
C code like the if(...) { } is not intended to be translated to the equivalent python. It is not trying to emulate full C executable semantics. It's really just trying to size data structures and determine layout for structures, and be able to call functions by name with argument checking and conversion. There are lots of kinds of macros that I can write in C that translate into pretty complex conditional logic in C (not in #ifdef), that I'm confident it can't handle - and are outside the scope of what it intends to do.

**Comment by Alan-R** [comment]
Not to mention FILE and LINE which are very specific to the context of C code, and don't translate at all to Python.

**Comment by scorp08** [comment]
thnks.  I could not get why UNCHECKED  is neccessary. And I guess it needs to put an `encode` because it is returning always to void

**Comment by Alan-R** [comment]
To clarify: If the code is not expressed as in the form a a pure function (including macro expansions), then ctypegen will not be able to handle it. It may have more restrictions than that, but it has _at least_ that restriction.

**Comment by scorp08** [comment]
as an independent question from this issue, related with  `UNCHECKED`, why do we need to control return type of `Cfunctypes` ?

**Comment by Alan-R** [comment]
I'm not sure what you're asking...  But making a wild guess...

Did you mean Why does Python need to know the return type of a C function?

The answer to that is pretty simple - because C functions return a wide variety of types - of special interest are pointer types. And for Python to handle them correctly, it has to know exactly what kind of object the pointer is pointing at.

For example, in the Assimilation code, I return lots of different pointers to C structures, which in turn need to get freed (reference counts decremented) after the Python code is done with them.

**Comment by scorp08** [comment]
But I tried for example with `c-int` and `UNCHECKED `returned to `void` . The other types like `c_char_p` or `c_float ` is same. All returning `void`. Why ?

**Comment by Alan-R** [comment]
I suspect that (like before) a simple example would make it clear.

I use it with literally dozens of different types. They all work for me. So there's something different about what you're doing. Occasionally I have to cast the return result.  All my code that uses this (and all works great) is here: 
https://github.com/assimilation/assimilation-official/blob/rel_2_dev/cma/AssimCclasses.py

But I do recall having to do a lot of casting... Details escape me at this time of night, but the code has my version of correct answers in it. I'm not really a ctypesgen developer, much more of a user...

**Comment by scorp08** [comment]
Thnks for reply. I ve just entered ctypes.c_int, c_float , c_char_p etc. as a parameter to UNCHECKED and all returned void. So do I need to do anything else ?

**Comment by Alan-R** [comment]
What sample C header file causes incorrect behaviors when translated to Python by ctypesgen?

**Comment by scorp08** [comment]
this https://github.com/kanzure/brlcad/blob/master/include/raytrace.h

**Comment by scorp08** [comment]
I tried `UNCHECKED `independently as regular function, but no matter what input gets, all return `void`. So in `CFUNCTYPE` that must be return for example `c_int`, returned `void`. So I put a   `__type__.encode()`

**Comment by Alan-R** [comment]
That header file is 8000 lines and includes a dozen other headers that you did not supply. That's not a small sample C header file, nor did you say what you were using from it, nor what the problem is.  UNCHECKED is not a function to be called. You need to call things in your header file. UNCHECKED is not in your header file.

What function are you trying to call _in your header file_, what did you expect to happen, and what happened instead?

Do not try and call UNCHECKED directly. Stop asking about calling it directly. No questions about that are appropriate.
